name: Build and deploy Flask app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Run tests using pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Run the tests with pytest

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./* 
          echo "venv" >> .gitignore

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: flask-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: flask-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'AIChatbot'  # Replace with your Azure Web App name
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}

